# Generated by Django 3.1.7 on 2021-03-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='user',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='house',
            name='registered_p',
            field=models.JSONField(default=dict),
        ),
    ]
