# Generated by Django 3.2 on 2021-04-14 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210318_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
