# Generated by Django 3.2 on 2021-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_house_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='profile',
            new_name='owner',
        ),
    ]
