# Generated by Django 3.2 on 2021-04-19 23:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_house_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='image',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='house',
            name='res_places',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
